let revenueTooltips = [
	{name: "Medical Center", info: "A large, not-for-profit regional medical center, including multiple hospitals, labs and clinics. Income comes from patients, medical insurance companies, and government programs like medicare."},
	{name: "Student Fees", info: "Fees are dedicated to specific services, such as athletic facilities, bus service (UNITRANS), student organizations, the CoHo and Student Community Center, etc. "},
	{name: "State of California", info: "General funds given by the taxpayers of California, appropriated annualy by the state legislature. General funds are not dedicated to specific services. "},
	{name: "Tuition", info: "Students pay tuition to attend the University. Non-California residents pay about twice as much as residents.  Tuition is also general funds."},
	{name: "Research Grants and Contracts", info: "Government and industry funds given to faculty and graduate students to perform research projects. These include up to 50% overhead in addition to the cost of the research. "},
	{name: "Pell Grants", info: "Federal grants for tuition and living expenses for low-income students. Percentage of students with Pell grants is a good way to measure who a University serves; at UCD, it's 34%; at Cal Tech it's 14%; at Sac State it's 71%."},
	{name: "Non-educational Services", info: "Services other than education that people pay for, like dorms, dining, parking, etc.  At UC Davis, this also includes almost $500M of revenue generated by medical school faculty, or 8%, making this category look really big."},
	{name: "Gifts, Endowments, Interest, Etc.", info: "Endowments are past gifts that were invested to provide income; interest is earned on other savings. The Museum is the direct result of a $10M gift from Jan Shrem and Maria Manetti Shrem."}]

export default revenueTooltips;
